import json
import os
from pathlib import Path

import pytest

from ragops.cli import main
from ragops.demo import write_demo


def test_demo_writes_blocked_candidate_and_reviewable_reports(tmp_path: Path) -> None:
    summary = write_demo(tmp_path / "demo")

    assert summary["demo_completed"] is True
    assert summary["candidate_decision"] == "BLOCK"
    assert "citation_coverage_regression" in summary["failed_gates"]
    html = (tmp_path / "demo" / "release-report.html").read_text(encoding="utf-8")
    assert "RAGOps regression report" in html
    assert "Generated by" in html
    assert "https://github.com/thangldw/ragops" in html


def test_demo_cli_returns_success_for_expected_block(monkeypatch, capsys, tmp_path: Path) -> None:
    output = tmp_path / "quickstart"
    monkeypatch.setattr("sys.argv", ["ragops", "demo", "--output", str(output)])

    assert main() == 0
    summary = json.loads(capsys.readouterr().out)
    assert summary["candidate_decision"] == "BLOCK"
    assert (output / "release-report.md").is_file()


def test_demo_refuses_existing_output_without_force(tmp_path: Path) -> None:
    output = tmp_path / "demo"
    output.mkdir()

    with pytest.raises(FileExistsError, match="already exists"):
        write_demo(output)


def test_demo_force_replaces_regular_files(tmp_path: Path) -> None:
    output = tmp_path / "demo"
    output.mkdir()
    (output / "release-report.md").write_text("old", encoding="utf-8")

    summary = write_demo(output, force=True)

    assert summary["candidate_decision"] == "BLOCK"
    assert (output / "release-report.md").read_text(encoding="utf-8").startswith(
        "# RAGOps regression check"
    )


@pytest.mark.skipif(not hasattr(os, "symlink"), reason="symlinks are unavailable")
def test_demo_refuses_symlinked_output_directory(tmp_path: Path) -> None:
    real_output = tmp_path / "real"
    real_output.mkdir()
    linked_output = tmp_path / "linked"
    linked_output.symlink_to(real_output, target_is_directory=True)

    with pytest.raises(FileExistsError, match="symlinked demo output directory"):
        write_demo(linked_output, force=True)


@pytest.mark.skipif(not hasattr(os, "symlink"), reason="symlinks are unavailable")
def test_demo_refuses_symlinked_child_without_overwriting_target(tmp_path: Path) -> None:
    output = tmp_path / "demo"
    output.mkdir()
    victim = tmp_path / "victim.md"
    victim.write_text("SAFE", encoding="utf-8")
    (output / "release-report.md").symlink_to(victim)

    with pytest.raises(FileExistsError, match="symlinked demo output file"):
        write_demo(output, force=True)

    assert victim.read_text(encoding="utf-8") == "SAFE"
